idx: 2
op_list:
- data:
  - '509'
  - '639'
  op_type: move
- data:
  - '683'
  - '639'
  op_type: move
- data:
  - '730'
  - '660'
  op_type: move
- data:
  - '767'
  - '674'
  op_type: move
tp_area_id: production_area_building_west_side
tp_name: 通往物流仓储区的入口
