template_name: "速切模板-潘引壶"
handlers:
  - states: "[前台-潘引壶]"
    sub_handlers:
      - states: "[自定义-黄光切人, 0, 1]"
        operations:
          - operation_template: "潘引壶-支援攻击"

      - states: "[自定义-红光闪避, 0, 1]"
        operations:
          - operation_template: "通用-闪A"

      - states: "[按键可用-连携技, 0, 0.5]"
        operations:
          - operation_template: "潘引壶-连携攻击"

      # 防呆
      - states: "([按键-切换角色-下一个, 0, 0.3]|[按键-切换角色-上一个, 0, 0.3])"
        debug_name: "切人后等待"
        sub_handlers:
          - states: "[潘引壶-终结技可用]"
            operations:
              - operation_template: "潘引壶-终结技"

          - states: "[按键可用-快速支援, 0, 0.5]"
            operations:
              - operation_template: "通用-快速支援"

      - states: "![自定义-连携换人, -10, 10]"
        sub_handlers:
          - states: "[潘引壶-终结技可用]"
            operations:
              - operation_template: "潘引壶-终结技"

      - states: "[潘引壶-特殊技可用]"
        debug_name: "熊猫只有合轴"
        operations:
          - operation_template: "潘引壶-特殊攻击合轴"

      - states: ""
        debug_name: "没能量了"
        operations:
          - op_name: "按键-普通攻击"
            post_delay: 0.1
            repeat: 10
          - op_name: "设置状态"
            state_list: ["自定义-速切结束"]