template_name: "速切模板-奥菲丝"
handlers:
  - states: "[前台-奥菲丝]"
    sub_handlers:
      - states: "[自定义-黄光切人, 0, 1]"
        operations:
          - operation_template: "通用-支援攻击"

      - states: "[自定义-红光闪避, 0, 1]"
        operations:
          - operation_template: "通用-闪A"

      - states: "[按键可用-连携技, 0, 0.5]"
        operations:
          - operation_template: "通用-连携攻击"

      # 防呆
      - states: "([按键-切换角色-下一个, 0, 0.3]|[按键-切换角色-上一个, 0, 0.3])"
        debug_name: "切人后等待"
        sub_handlers:
          - states: "[按键可用-快速支援, 0, 0.3]"
            operations:
              - op_name: "等待秒数"
                seconds: 0.3
          - states: ""
            operations:
              - op_name: "等待秒数"
                seconds: 0.3

      - states: "[奥菲丝-终结技可用] & ![自定义-奥菲丝-喷火中, 0 ,5.5]"
        operations:
          - operation_template: "奥菲丝-终结技"

      - states: "[自定义-奥菲丝-喷火中, 0 ,5.5]"
        interrupt_states: "[奥菲丝-蓄炎]{0, 60}"
        operations:
          - op_name: "设置状态"
            state_list: ["自定义-速切结束"]
          - op_name: "等待秒数"
            seconds: 5

      - states: "[奥菲丝-蓄炎]{100, 125}"
        interrupt_states: "[奥菲丝-蓄炎]{0, 100}"
        operations:
          - operation_template: "奥菲丝-特殊攻击合轴"

      - states: ""
        operations:
          - op_name: "设置状态"
            state_list: ["自定义-速切结束"]
          - operation_template: "奥菲丝-普通攻击"
